@arr=(1..10);
print "Initial array: @arr\n";
pop @arr;
print "After pop: @arr\n";
push @arr,(10);
print "After push: @arr\n";
shift @arr;
print "After shift: @arr\n";
unshift @arr,(1);
print "After unshift: @arr\n";
